### ISSUE TITLE
Error with Arduino IDE 

### ISSUE THREAD

**Issue by roncoa** [akaJes/AsyncPing#5]
Hello,
with Arduino IDE, IwIP 1.4 higher bandwidth, I have the following error.
While with Arduino IDE, IwIP 2 higher bandwidth my code is compiled without any errors.

What's the problem?

`C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp: In member function 'bool AsyncPing::begin(const IPAddress&, u8_t, u32_t)':
C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp:45:67: error: invalid conversion from 'u8_t (*)(void*, raw_pcb*, pbuf*, const ip_addr_t*) {aka unsigned char (*)(void*, raw_pcb*, pbuf*, const ip_addr*)}' to 'raw_recv_fn {aka unsigned char (*)(void*, raw_pcb*, pbuf*, ip_addr*)}' [-fpermissive]
     raw_recv(ping_pcb, _s_ping_recv, reinterpret_cast<void*>(this));
                                                                   ^
In file included from C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.h:6:0,
                 from C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp:2:
C:\Users\ronco\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/lwip/include/lwip/raw.h:84:18: error:   initializing argument 2 of 'void raw_recv(raw_pcb*, raw_recv_fn, void*)' [-fpermissive]
 void             raw_recv       (struct raw_pcb *pcb, raw_recv_fn recv, void *recv_arg)ICACHE_FLASH_ATTR;
                  ^
C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp: In member function 'u8_t AsyncPing::ping_recv(raw_pcb*, pbuf*, const ip_addr_t*)':
C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp:151:68: error: invalid conversion from 'const ip_addr_t* {aka const ip_addr*}' to 'ip_addr_t* {aka ip_addr*}' [-fpermissive]
         etharp_find_addr(NULL, addr, &_response.mac, &unused_ipaddr);
                                                                    ^
In file included from C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.h:7:0,
                 from C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp:2:
C:\Users\ronco\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/lwip/include/netif/etharp.h:186:6: error:   initializing argument 2 of 's8_t etharp_find_addr(netif*, ip_addr_t*, eth_addr**, ip_addr_t**)' [-fpermissive]
 s8_t etharp_find_addr(struct netif *netif, ip_addr_t *ipaddr,
      ^
C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp:151:68: error: invalid conversion from 'const ip_addr_t** {aka const ip_addr**}' to 'ip_addr_t** {aka ip_addr**}' [-fpermissive]
         etharp_find_addr(NULL, addr, &_response.mac, &unused_ipaddr);
                                                                    ^
In file included from C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.h:7:0,
                 from C:\Users\ronco\Documents\Arduino\libraries\AsyncPing-master\src\AsyncPing.cpp:2:
C:\Users\ronco\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/sdk/lwip/include/netif/etharp.h:186:6: error:   initializing argument 4 of 's8_t etharp_find_addr(netif*, ip_addr_t*, eth_addr**, ip_addr_t**)' [-fpermissive]
 s8_t etharp_find_addr(struct netif *netif, ip_addr_t *ipaddr,
      ^`

`exit status 1
Error compiling for Generic ESP8266 Module card.`

**Comment by devyte** [comment]
lwip 1.4 is legacy, and has already been pulled out in the latest master branch of the core. I suggest migrating your code to v2.

**Comment by roncoa** [comment]
Thanks.
